// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgKjbIJe8s6Fw25phFWe8RfkAhfbSbrfo',
    appId: '1:353319954371:web:426265d9ad63e4376f3f76',
    messagingSenderId: '353319954371',
    projectId: 'mini-chat-app-2736',
    authDomain: 'mini-chat-app-2736.firebaseapp.com',
    storageBucket: 'mini-chat-app-2736.appspot.com',
    measurementId: 'G-DKLWWW4BWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3kpneBmcMEBJ1zscraRxQd8-fnLXnYiM',
    appId: '1:353319954371:android:b1b62051df75e7ff6f3f76',
    messagingSenderId: '353319954371',
    projectId: 'mini-chat-app-2736',
    storageBucket: 'mini-chat-app-2736.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK0etlxehud24AxWHWKCQwVI8OA0cfzzo',
    appId: '1:353319954371:ios:e5d08d98da17959a6f3f76',
    messagingSenderId: '353319954371',
    projectId: 'mini-chat-app-2736',
    storageBucket: 'mini-chat-app-2736.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK0etlxehud24AxWHWKCQwVI8OA0cfzzo',
    appId: '1:353319954371:ios:e5d08d98da17959a6f3f76',
    messagingSenderId: '353319954371',
    projectId: 'mini-chat-app-2736',
    storageBucket: 'mini-chat-app-2736.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgKjbIJe8s6Fw25phFWe8RfkAhfbSbrfo',
    appId: '1:353319954371:web:c65fa6cb8bd4a1e36f3f76',
    messagingSenderId: '353319954371',
    projectId: 'mini-chat-app-2736',
    authDomain: 'mini-chat-app-2736.firebaseapp.com',
    storageBucket: 'mini-chat-app-2736.appspot.com',
    measurementId: 'G-7PTF7Z1W1C',
  );
}
